### PR TITLE
Added a project styles file , changes in the fonts

### PR DESCRIPTION
**Pull request by brendangaturu**
Project styles file
Comments applied on the same

### CODE REVIEW

**Review by MawiraIke — APPROVED** [review]
Will make some few changes to this concerning standard Dart syntax, otherwise, seems fine by me. Kudos. 👍

**Review by MawiraIke — CHANGES_REQUESTED** [review]
Seems like this cannot be merged successfully, could you please pull the latest changes from master and then do a manual merge on your branch and then push them. 
I pushed some code yesterday, it must be having conflicts with your code. 
Thanks.

**Review by MawiraIke — APPROVED** [review]
I have resolved it, merging shortly.

**Comment by brendangaturu** [comment]
Sure great, was wondering if a conflict can occur when my branch is n
commits behind an upstream.  Let me update my branch and pull your  changes
too.

**Comment by MawiraIke** [comment]
Yeah it can occur, but that's partly the issue. The issue is mostly when the different codes have a conflict. i.e We both edited the same piece of code and git does not know which version to include. Great.

**Pull request merged**
